services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: porcini_api
    ports:
      - "8787:8787"
  web:
    image: nginx:stable-alpine
    container_name: porcini_web
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - api
