services:
  - type: web
    name: porcinicast-api-advanced
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      # Aggiungi qui le tue API keys se necessarie
      # - key: OPENWEATHER_API_KEY
      #   value: "your_key_here"
      # - key: CDS_API_KEY
      #   value: "your_cds_key"
    healthCheckPath: /api/health
    
    # Configurazioni di scaling per performance
    disk:
      name: porcini-data
      sizeGB: 1
      mountPath: /app/data
