services:
  - type: web
    name: porcini-api
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars: []
    repo: https://example.com/your/repo  # (aggiorna con il tuo repo)
    rootDir: backend
  - type: web
    name: porcini-web
    env: static
    plan: free
    buildCommand: ""
    staticPublishPath: frontend
    routes:
      - type: rewrite
        source: /api/(.*)
        destination: https://porcini-api.onrender.com/api/$1
